const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');const cache={};
function load(name){if(cache[name])return cache[name];const output=ts.transpileModule(fs.readFileSync(path.resolve('app',name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const e={};new Function('require','exports',output)(id=>load(id.replace('./','')),e);return cache[name]=e;}
const S=load('course-state'),Q=load('score-sync');
function storage(){const m=new Map();global.localStorage={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};}
function state(){const s=S.fresh({classroom:'測試',seat:'1',name:'測試同學'});s.sessionId='test-session-0001';s.started=true;return s;}
test('成績摘要保留首次與最高分，未作答為 null',()=>{const s=state();s.activities['game-one']=[{score:30},{score:60}];s.activities['assessment-one']=[{score:70},{score:100}];const p=Q.scoreSnapshot(s);assert.equal(p.scores.assessmentOne,70);assert.equal(p.scores.gameOne,30);assert.equal(p.scores.gameOneBest,60);assert.equal(p.scores.assessmentTwo,null);});
test('重試沿用事件 ID，新摘要替換未送出舊摘要',()=>{storage();const s=state();Q.enqueue(Q.scoreSnapshot(s));const first=Q.readQueue()[0];Q.enqueue(Q.scoreSnapshot(s));assert.equal(Q.readQueue().length,1);assert.equal(Q.readQueue()[0].eventId,first.eventId);s.explored.push('guide');Q.enqueue(Q.scoreSnapshot(s));assert.equal(Q.readQueue().length,1);assert.notEqual(Q.readQueue()[0].eventId,first.eventId);Q.acknowledge(first);assert.equal(Q.readQueue().length,1);});
test('換人仍保留先前待傳內容，確認寫入後不再重傳',()=>{storage();const a=Q.scoreSnapshot(state());Q.enqueue(a);const b={...a,sessionId:'test-session-0002',identity:{...a.identity,name:'另一位'}};Q.enqueue(b);assert.equal(Q.readQueue().length,2);Q.acknowledge(Q.readQueue()[0]);Q.enqueue(a);assert.equal(Q.readQueue().length,1);assert.equal(Q.readQueue()[0].identity.name,'另一位');});
test('只有相符事件的明確成功回條才算寫入',async()=>{const item={...Q.scoreSnapshot(state()),eventId:'event-test-001'};global.fetch=async()=>({ok:true,json:async()=>({ok:true,eventId:'wrong'})});await assert.rejects(()=>Q.sendScore('https://example.test',item));global.fetch=async()=>({ok:true,json:async()=>({ok:true,eventId:item.eventId})});assert.equal((await Q.sendScore('https://example.test',item)).ok,true);});
