'use client';
import {useEffect,useRef,useState} from 'react';
import {CHALLENGE,GAME_ONE,GAME_TWO,shuffle,type GameQuestion} from './course-data';
import type {ActivityResult} from './course-state';
import {AdventureScene,DesignIcon} from './design-elements';
import {ChallengeLeaderboard} from './challenge-leaderboard';

export function challengePoints(position:number){return Math.max(500,Math.floor(5000-45*position));}
export function Game({variant,history,onFinish}:{variant:1|2;history:ActivityResult[];onFinish:(r:ActivityResult)=>void}){
 const bank=variant===1?GAME_ONE:GAME_TWO;
 const [started,setStarted]=useState(false);const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<string[]>([]);const [options,setOptions]=useState<string[]>([]);const [picked,setPicked]=useState('');const [result,setResult]=useState<ActivityResult>();const lock=useRef(false);const advanceLock=useRef(false);
 const q=bank[index];const score=answers.filter((a,i)=>a===bank[i].answer).length*10;
 const start=()=>{setIndex(0);setAnswers([]);setPicked('');setOptions(shuffle(bank[0].options));setResult(undefined);setStarted(true);lock.current=false;};
 const pick=(a:string)=>{if(lock.current)return;lock.current=true;advanceLock.current=false;setPicked(a);setAnswers(v=>[...v,a]);};
 const next=()=>{if(!picked||advanceLock.current)return;advanceLock.current=true;if(index===bank.length-1){const correct=answers.map((a,i)=>a===bank[i].answer);const r={score:correct.filter(Boolean).length*10,answers,correct,at:new Date().toISOString()};setResult(r);onFinish(r);setStarted(false);}else{setIndex(i=>i+1);setOptions(shuffle(bank[index+1].options));setPicked('');lock.current=false;}};
 return <section className={`game-shell game-${variant}`}><div className="game-hud"><span className="label">{variant===1?'NUTRIENT QUEST':'EVIDENCE QUEST'}</span><span>6 回合・每題 10 分</span><strong>本次 {score} 分</strong></div>
 <div className={`game-stage ${started?'playing':'waiting'}`}><AdventureScene/><div className="scene-bubble">{started?'點選通道即可作答。':'帶著證據，開始探索！'}</div><div className="scene-hud"><span><DesignIcon name="flag"/>{variant===1?'養分任務闖關':'檢測判斷挑戰'}</span><b>第 {index+1} 回合</b><strong>本次 {score} 分</strong></div>
 {!started&&!result?<div className="game-welcome"><span className="eyebrow">帶著知識，踏上探險</span><h2>{variant===1?'選對養分，開啟通道':'瞄準有證據的結論'}</h2><p>{variant===1?'每道線索有三條通道，選擇符合功能的養分。':'讀完觀察紀錄，選出證據支持的結論。'}<br/>答題後可讀解析，再進下一回合。遊戲沒有倒數限制。</p><button className="primary" onClick={start}>{history.length?'再玩一次':'開始探險'} →</button></div>:result?<div className="game-welcome game-finished"><span className="eyebrow">任務完成</span><h2>{result.score} <small>／ 60 分</small></h2><p>答對 {result.correct.filter(Boolean).length}／6 題，每一次觀察都讓判斷更精準。</p><button className="primary" onClick={start}>再次挑戰</button></div>:<><div className="game-question"><DesignIcon name="search"/><h2>{q.prompt}</h2></div><div className="scene-hint">選對通道，查看理由</div><div className={variant===1?'portal-row':'target-row'}>{options.map((a,i)=><button className={`game-choice ${picked===a?'chosen':''} ${picked&&a===q.answer?'right-answer':''}`} key={a} disabled={!!picked} onClick={()=>pick(a)}><span className="portal-symbol" aria-hidden="true">{['◇','◉','✦'][i]}</span><span>{a}</span><small>{variant===1?'進入通道':'選擇結論'}</small></button>)}</div>{picked&&<div className="game-feedback" role="status"><strong>{picked===q.answer?'答對了！＋10 分':'這次未得分，記住這條線索。'}</strong><p>{q.reason}</p><button className="primary" onClick={next}>{index===5?'查看本次成果':'下一回合 →'}</button></div>}</>}

 </div><div className="game-history"><p>首次：<strong>{history[0]?`${history[0].score} 分`:'尚未完成'}</strong></p><p>最高：<strong>{history.length?`${Math.max(...history.map(r=>r.score))} 分`:'—'}</strong></p><p>已完成 {history.length} 次</p></div>
 {result&&<details className="card"><summary>回顧這次的 6 條線索</summary>{bank.map((q,i)=><p key={q.prompt}><strong>{i+1}. {result.correct[i]?'✓':'待複習'}　{q.prompt}</strong><br/>你的答案：{result.answers[i]}。{q.reason}</p>)}</details>}</section>;
}

export function Challenge({history,onFinish}:{history:ActivityResult[];onFinish:(r:ActivityResult)=>void}){
 const [phase,setPhase]=useState<'ready'|'running'|'paused'|'feedback'|'finished'>('ready');const [index,setIndex]=useState(0);const [position,setPosition]=useState(0);const [lives,setLives]=useState(3);const [score,setScore]=useState(0);const [notice,setNotice]=useState('');const [options,setOptions]=useState<string[]>([]);
 const runtime=useRef({phase:'ready',index:0,position:0,lives:3,score:0,answers:[] as string[],correct:[] as boolean[]});
 const finish=(r:typeof runtime.current)=>{r.phase='finished';setPhase('finished');onFinish({score:r.score,answers:[...r.answers],correct:[...r.correct],at:new Date().toISOString()});};
 const resolveRef=useRef<(a:string|null)=>void>(()=>{});
 resolveRef.current=(answer:string|null)=>{const r=runtime.current;if(r.phase!=='running')return;r.phase='feedback';const q=CHALLENGE[r.index];const correct=answer===q.answer;let gain=0;if(correct){gain=challengePoints(r.position);r.score+=gain;}else{r.lives--;if(answer!==null)r.score=Math.max(0,r.score-1000);}r.answers.push(answer??'逾時');r.correct.push(correct);setScore(r.score);setLives(r.lives);setNotice(`第 ${r.index+1} 題：${answer===null?'逾時，扣 1 次生命，不扣分。':correct?`答對！＋${gain.toLocaleString()} 分。`:'答錯，扣 1 次生命與 1,000 分（最低為 0）。'} ${q.reason}`);advance();};
 useEffect(()=>{const id=window.setInterval(()=>{const r=runtime.current;if(r.phase!=='running')return;r.position=Math.min(100,r.position+.35+r.index*.015);setPosition(r.position);if(r.position>=100)resolveRef.current(null);},20);const hide=()=>{if(document.hidden&&runtime.current.phase==='running'){runtime.current.phase='paused';setPhase('paused');}};document.addEventListener('visibilitychange',hide);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',hide);};},[]);
 const start=()=>{runtime.current={phase:'running',index:0,position:0,lives:3,score:0,answers:[],correct:[]};setIndex(0);setPosition(0);setLives(3);setScore(0);setNotice('');setOptions(shuffle(CHALLENGE[0].options));setPhase('running');};
 const pause=()=>{const r=runtime.current;if(r.phase==='running'){r.phase='paused';setPhase('paused');}else if(r.phase==='paused'){r.phase='running';setPhase('running');}};
 const advance=()=>{const r=runtime.current;if(r.phase!=='feedback')return;if(r.lives===0||r.index===CHALLENGE.length-1){finish(r);return;}r.index++;r.position=0;r.phase='running';setIndex(r.index);setPosition(0);setOptions(shuffle(CHALLENGE[r.index].options));setPhase('running');};
 return <section className="challenge-shell"><div className="challenge-intro card"><span className="label">限時挑戰・全體學生英雄榜</span><h2>快一點判斷，也要判斷正確</h2><p>共 12 題、3 次生命。指標到終點前選出養分類別；越早答對，得分越高。作答後立即進入下一題，上一題回饋會保留在下方；最後一題或生命用完會自動結算。</p><details><summary>查看計分規則</summary><p>指標每 20 毫秒前進 0.35＋題目索引×0.015（索引從 0 開始）。答對得分為 5,000－45×位置，取整數，最低 500 分。答錯扣 1,000 分與 1 次生命；逾時只扣生命。分數最低 0 分。生命用完或答完題庫即結束。</p></details></div>
 <div className="challenge-arena"><div className="challenge-hud"><span>第 {index+1}／12 題</span><strong>{score.toLocaleString()} 分</strong><span>生命 {lives}／3</span>{['running','paused'].includes(phase)&&<button className="outline" onClick={pause}>{phase==='paused'?'繼續計時':'暫停'}</button>}</div>
 {phase==='ready'?<div className="challenge-welcome"><span className="challenge-star">✦</span><h2>準備好迎接極限挑戰了嗎？</h2><p>開始後指標會移動，可隨時暫停。切換分頁也會自動暫停。</p><button className="primary" onClick={start}>開始計時挑戰</button></div>:phase==='finished'?<div className="challenge-welcome"><span className="challenge-star">✦</span><h2>{score.toLocaleString()} 分</h2><p>完成 {runtime.current.answers.length} 題，答對 {runtime.current.correct.filter(Boolean).length} 題。</p><button className="primary" onClick={start}>再挑戰一次</button></div>:<><div className="challenge-track" role="progressbar" aria-label="本題時間進度" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(position)}><div style={{width:`${position}%`}}/><span style={{left:`${Math.min(position,94)}%`}}>◆</span></div><div className="track-labels"><span>快速回答，爭取高分</span><span>終點</span></div><h2>{CHALLENGE[index].prompt}</h2>{phase==='paused'?<div className="pause-panel"><strong>已暫停</strong><p>時間停止，準備好再繼續。</p><button className="primary" onClick={pause}>繼續計時</button></div>:<div className="challenge-choices">{options.map(a=><button key={a} disabled={phase!=='running'} onClick={()=>resolveRef.current(a)}>{a}</button>)}</div>}</>}
 {notice&&<div className="challenge-feedback" role="status"><p>{notice}</p></div>}</div><ChallengeLeaderboard/></section>;
}
