'use client';
import {useState} from 'react';
import {Art,CellDiagram,LabDrawing,NutrientIllustration} from './course-art';
import {NUTRIENTS} from './course-data';
import {DesignIcon} from './design-elements';

const FUNCTIONS=[['醣類','可供能，也可構成植物細胞壁。','澱粉、肝糖、纖維素'],['蛋白質','可供能，也是肌肉、毛髮中的構成材料。','構成與供能'],['脂質','可供能、儲存能量，皮下脂質有助保溫。','儲能與保溫'],['水','不供能，是許多物質溶解與反應的環境。','維持反應環境'],['礦物質','不供能，可構成組織並調節生理機能。','鈣、磷、鐵'],['維生素','不供能，少量即對生理機能有重要作用。','維生素 A、維生素 C']];

export function Guide({onDone,done}:{onDone:()=>void} & {done:boolean}){
 const [value,setValue]=useState('');const [checked,setChecked]=useState(false);
 return <><div className="guide-title"><p>用觀察、實驗與證據，認識食物中的養分，發現它們如何幫助我們維持健康！</p><Art kind="scientist"/></div><div className="guide-columns"><section className="card guide-task-list"><h2><DesignIcon name="note"/>三個學習任務</h2><p className="guide-task-intro">循序完成任務，從生活中的食物出發，建構科學的證據與結論。</p>{[{title:'認識六大養分',text:'從常見食物中，認識醣類、蛋白質、脂質、維生素、礦物質和水的特徵與來源。',art:'food'},{title:'用試劑找線索',text:'透過簡單的科學檢測，使用試劑觀察樣本的變化，找出其中可能含有的養分。',art:'lab'},{title:'根據證據下結論',text:'整理觀察到的結果，判斷食物中含有哪些養分，並說明你的理由。',art:'evidence'}].map((t,i)=><article className={`guide-task task-${i}`} key={t.title}><b>{i+1}</b><div><h3>{t.title}</h3><p>{t.text}</p></div><Art kind={t.art as 'food'|'lab'|'evidence'}/>{i===0&&<small className="food-note">※ 一種食物可能含多種養分。</small>}</article>)}</section><aside className="guide-side"><section className="card guide-reminders"><h2><DesignIcon name="flag"/>操作小提醒</h2><ol className="instruction-list">{[['先選答案，再檢查','先動動腦想一想，選出你認為正確的答案，再按下「檢查答案」。'],['答錯可以重新作答','如果答錯了，沒關係！你可以重新思考，再試一次。'],['完成後前往下一頁','完成所有內容後，點擊「下一頁」，繼續你的學習旅程。']].map(([t,p],i)=><li key={t}><b>{i+1}</b><span className="reminder-symbol" aria-hidden="true">{['↖','⟳','→'][i]}</span><div><strong>{t}</strong><p>{p}</p></div></li>)}</ol></section><section className="card demo-card"><h2><DesignIcon name="flask"/>示範題：請選圓形</h2><p>以下是題目作答時的操作步驟示意。</p><div className="demo-stages"><div className="demo-choice"><span><b>1</b> 選擇</span><div className="shape-options">{['圓形','正方形','三角形'].map((s,i)=><button key={s} aria-label={s} aria-pressed={value===s} className={value===s?'selected':''} disabled={checked} onClick={()=>setValue(s)}><span aria-hidden="true">{['○','□','△'][i]}</span></button>)}</div></div><span className="demo-arrow">→</span><div className="demo-check"><span><b>2</b> 檢查</span><button className="primary" disabled={!value||checked} onClick={()=>{setChecked(true);if(value==='圓形')onDone();}}>檢查</button></div><span className="demo-arrow">→</span><div className="demo-revise"><span><b>3</b> 修正</span>{checked?<p className={value==='圓形'?'demo-right':'demo-wrong'} role="status">{value==='圓形'?'✓ 答對了！':'✕ 再試一次'}</p>:<p>提交後<br/>查看回饋</p>}{checked&&value!=='圓形'&&<button className="outline" onClick={()=>{setValue('');setChecked(false);}}>重新選擇</button>}</div></div>{done&&<small className="helper">✓ 已熟悉操作方式</small>}</section></aside></div></>;
}

export function Exploration({id,onDone,done}:{id:string;onDone:()=>void;done:boolean}){
 const [choices,setChoices]=useState<Record<string,string>>({});const [checked,setChecked]=useState(false);const [selection,setSelection]=useState('');const [result,setResult]=useState('');
 const choose=(key:string,v:string)=>{setChoices(c=>({...c,[key]:v}));setChecked(false);setResult('');};
 const complete=(message:string)=>{setChecked(true);setResult(message);onDone();};
 const label=<div className="exploration-heading"><span className="label">先探索，再練習</span><span>{done?'✓ 已完成探索':'探索尚未完成'}</span></div>;
 if(id==='nutrients')return <section className="card exploration">{label}<h2>有熱量，才有用嗎？</h2><p>先判斷六類養分是否能提供能量，再比較它們的功能。圖中食物為例子，一種食物可能含有多種養分。</p><div className="nutrient-classify">{FUNCTIONS.map(([n,,example],i)=><article key={n}><NutrientIllustration kind={n}/><h3>{n}</h3><p>{example}</p><label><span className="sr-only">{n}能否供能</span><select value={choices[n]||''} onChange={e=>choose(n,e.target.value)}><option value="">先做判斷</option><option>可提供能量</option><option>不能提供能量</option></select></label>{checked&&<p className="reveal-text">{FUNCTIONS[i][1]}</p>}</article>)}</div><button className="primary" disabled={NUTRIENTS.some(n=>!choices[n])} onClick={()=>{setChecked(true);setResult('請對照各卡的功能說明：不供能，仍可能是身體運作必需的養分。');}}>比較功能</button>{checked&&<div className="discovery"><p>{result}</p><label>修正廣告「沒有熱量就沒有營養」<select value={selection} onChange={e=>setSelection(e.target.value)}><option value="">請選擇修正</option><option>不供能養分仍有重要功能</option><option>所有養分都能供能</option></select></label><button className="outline" disabled={!selection} onClick={()=>selection==='不供能養分仍有重要功能'?complete('修正完成：供能與生理功能要分開思考。'):setResult('再看水、礦物質與維生素的功能。')}>確認修正</button></div>}</section>;
 if(id==='materials'){
  const scenes=[{name:'植物細胞壁',answer:'構成材料',text:'纖維素屬於醣類，是植物細胞壁的重要材料。'},{name:'肌肉與毛髮',answer:'構成材料',text:'肌肉與毛髮中含蛋白質，說明蛋白質不只有供能功能。'},{name:'皮下脂質',answer:'保溫',text:'皮下脂質有助減少熱量散失，也可以儲存能量。'}];const active=scenes.find(x=>x.name===selection)||scenes[0];
  return <section className="card exploration">{label}<h2>切換觀察：養分也能成為身體材料</h2><div className="tab-buttons">{scenes.map(s=><button key={s.name} className={active===s?'selected':''} onClick={()=>{setSelection(s.name);setChecked(false);setResult('');}}>{s.name}</button>)}</div><div className="explore-split"><div>{active.name==='植物細胞壁'?<CellDiagram/>:active.name==='肌肉與毛髮'?<svg className="body-art" viewBox="0 0 420 220" role="img" aria-label="肌肉纖維與毛髮的示意"><rect width="420" height="220" rx="15" fill="#fff0e6"/>{[0,1,2,3].map(i=><path key={i} d={`M50 ${55+i*32}q100-45 170 0t150 0`} fill="none" stroke={i%2?'#e79680':'#bd5e60'} strokeWidth="19"/>)}<text x="210" y="203" textAnchor="middle" fill="#633c49" fontSize="18">蛋白質是肌肉中的材料之一</text></svg>:<svg className="body-art" viewBox="0 0 420 220" role="img" aria-label="皮膚下方脂質層的保溫示意"><rect width="420" height="220" rx="15" fill="#f3f8fc"/><path d="M30 70h360" stroke="#e4a085" strokeWidth="30"/><path d="M30 98h360" stroke="#f3c7b3" strokeWidth="25"/>{[0,1,2,3,4,5,6,7].map(i=><circle key={i} cx={53+i*45} cy="141" r="24" fill="#f2cf66" stroke="#ddb249"/>)}<text x="210" y="202" textAnchor="middle" fill="#765627" fontSize="18">皮下脂質有助減少熱量散失</text></svg>}</div><div><h3>{active.name}</h3><label>這個情境主要呈現哪一用途？<select value={choices[active.name]||''} onChange={e=>choose(active.name,e.target.value)}><option value="">請選擇</option><option>構成材料</option><option>保溫</option><option>所有養分都只有供能用途</option></select></label><button className="primary" disabled={!choices[active.name]} onClick={()=>{setChecked(true);setResult(active.text);if(choices[active.name]===active.answer)choose('viewed-'+active.name,'yes');setResult(active.text);setChecked(true);}}>查看功能</button>{checked&&<p className="discovery">{result}</p>}</div></div><p>已解讀 {scenes.filter(s=>choices['viewed-'+s.name]).length}／3 個情境。</p><button className="outline" disabled={scenes.some(s=>!choices['viewed-'+s.name])} onClick={()=>complete('三個情境完成：養分的功能可能不只一種。')}>完成三個情境比較</button></section>;
 }
 if(id==='essentials')return <section className="card exploration">{label}<h2>身體缺少了哪個幫手？</h2><p>將情境配到適合的養分類別，再檢查「只要熱量就夠了」的說法。</p><div className="function-cards">{[['許多細胞反應需要的溶解環境','水'],['骨骼、牙齒中的鈣與磷','礦物質'],['需求少但維持生理機能，教材例子為維生素 A、維生素 C','維生素']].map(([s,a])=><label key={s}><NutrientIllustration kind={a} context/><span>{s}</span><select value={choices[s]||''} onChange={e=>choose(s,e.target.value)}><option value="">選擇養分</option>{['水','礦物質','維生素'].map(n=><option key={n}>{n}</option>)}</select>{checked&&<small>{choices[s]===a?'配對正確':`再想一想：本情境與${a}有關。`}</small>}</label>)}</div><button className="primary" disabled={Object.keys(choices).length<3} onClick={()=>{setChecked(true);setResult('水提供反應環境，礦物質與維生素也有必要功能。只補供能養分並不完整。');if(choices['許多細胞反應需要的溶解環境']==='水'&&choices['骨骼、牙齒中的鈣與磷']==='礦物質'&&choices['需求少但維持生理機能，教材例子為維生素 A、維生素 C']==='維生素')onDone();}}>檢查配對</button>{checked&&<p className="discovery">{result}</p>}</section>;
 if(id==='iodine')return <section className="card exploration">{label}<h2>先預測，再觀察</h2><div className="explore-split"><div><LabDrawing kind="iodine" done={checked}/><div className="field-grid">{['澱粉液','水'].map(n=><label key={n}>{n}的預測<select disabled={checked} value={choices[n]||''} onChange={e=>choose(n,e.target.value)}><option value="">請選擇顏色</option><option>黃褐色</option><option>藍黑色或紫紅色</option></select></label>)}</div><div className="actions"><button className="primary" disabled={!choices['澱粉液']||!choices['水']||checked} onClick={()=>complete('比較完成。澱粉也可能呈紫紅色，本次以藍黑色示意。')}>滴入碘液</button>{checked&&<button className="outline" onClick={()=>{setChoices({});setChecked(false);setResult('');}}>重新觀察</button>}</div></div><div><ObservationTable rows={['澱粉液','水'].map((n,i)=>[n,choices[n]||'—',checked?(i===0?'藍黑色':'黃褐色'):'尚未操作'])}/><div className="discovery"><h3>{checked?'你找到的證據':'想一想'}</h3><p>{checked?'水加碘液後維持黃褐色，沒有出現相同的藍黑色變化。比較兩組可支持變色與澱粉有關。':'兩個樣本都加入碘液，如果只有其中一個變色，差異可能來自什麼？'}</p>{checked&&<p>{choices['澱粉液']==='藍黑色或紫紅色'&&choices['水']==='黃褐色'?'預測與觀察一致。':'請比較預測與觀察，修正原本的想法。'}{result}</p>}</div></div></div><p className="helper">虛擬操作；實際使用試劑須由老師指導。</p></section>;
 if(id==='benedict'){
  const mixed=choices.mixed==='yes';const heated=choices.heated==='yes';
  return <section className="card exploration">{label}<h2>混合就能下結論嗎？</h2><div className="explore-split"><div><LabDrawing kind="benedict" done={mixed} heated={heated}/><div className="field-grid">{['葡萄糖液','水'].map(n=><label key={n}>{n}完成流程後的預測<select disabled={mixed} value={choices[n]||''} onChange={e=>choose(n,e.target.value)}><option value="">先選擇顏色</option><option>維持淡藍色</option><option>呈橙紅色</option></select></label>)}</div><ol className="procedure"><li>各取 2 mL 葡萄糖液與水。</li><li>各加入 2 mL 本氏液並混勻。</li><li>放入同一條件水浴後觀察。</li></ol><div className="actions"><button className="primary" disabled={!choices['葡萄糖液']||!choices['水']||mixed} onClick={()=>{setChoices(c=>({...c,mixed:'yes'}));setResult('已混合，尚未加熱。此時條件不足，不能直接下陰性結論。');}}>加入本氏液並混勻</button><button className="primary" disabled={!mixed||heated} onClick={()=>{setChoices(c=>({...c,heated:'yes'}));complete('已完成隔水加熱。葡萄糖組呈橙紅色，水組維持淡藍色。');}}>隔水加熱</button></div></div><div><ObservationTable rows={['葡萄糖液','水'].map((n,i)=>[n,choices[n]||'—',heated?(i===0?'橙紅色':'淡藍色'):mixed?'尚未完成加熱':'尚未操作'])}/><div className="discovery" role="status"><h3>{heated?'檢測條件完成':'留意檢測條件'}</h3><p>{result||'先預測，再混合與加熱。顏色僅作定性示意，不能換算精確糖量。'}</p></div>{heated&&<button className="outline" onClick={()=>{setChoices({});setChecked(false);setResult('');}}>重新操作</button>}</div></div><p className="helper">此為虛擬水浴；實際使用試劑與加熱設備須由老師指導。</p></section>;
 }
 if(id==='fair-test')return <section className="card exploration">{label}<h2>修好這個不公平的實驗</h2><p>甲組固定：2 mL 葡萄糖液＋2 mL 本氏液，隔水加熱。乙組初始用 4 mL 水、1 mL 本氏液、不加熱。請修正乙組。</p><div className="fair-grid"><div className="reference-group"><LabDrawing kind="benedict"/><strong>甲：實驗組</strong><p>待比較的是「樣本種類」。</p></div><div className="control-group"><h3>乙：水對照組</h3>{[['volume','水的體積',['4 mL','2 mL']],['reagent','本氏液體積',['1 mL','2 mL']],['heat','加熱條件',['不加熱','相同水浴條件']]].map(([key,label,opts])=><label key={key as string}>{label as string}<select value={choices[key as string]||(opts as string[])[0]} onChange={e=>choose(key as string,e.target.value)}>{(opts as string[]).map(x=><option key={x}>{x}</option>)}</select></label>)}<button className="primary" onClick={()=>choices.volume==='2 mL'&&choices.reagent==='2 mL'&&choices.heat==='相同水浴條件'?complete('修復成功：只改變樣本種類，其他條件保持一致。'):setResult('還有條件不同。比較甲、乙的樣本量、試劑量及加熱條件。')}>檢查是否公平</button></div></div>{result&&<p role="status" className="discovery">{result}</p>}</section>;
 if(id==='samples'){
  const samples=[{id:'白飯樣本',mark:'甲',color:'rice',iodine:'藍黑色',benedict:'淡藍色'},{id:'水果樣本',mark:'乙',color:'fruit',iodine:'黃褐色',benedict:'橙紅色'},{id:'匿名樣本 C',mark:'丙',color:'unknown',iodine:'黃褐色',benedict:'淡藍色'}];const active=samples.find(s=>s.id===selection)||samples[0];const shown=choices['seen-'+active.id];
  return <section className="card exploration">{label}<h2>每份樣本分兩份，分別檢測</h2><p className="data-note">以下為教學用虛擬結果，不能代表所有白飯或水果的實際成分。</p><div className="sample-process"><span>加 10 mL 水研磨</span><b>→</b><span>雙層紗布取液</span><b>→</b><span>取 2 mL，分別檢測</span></div><div className="tab-buttons sample-tabs">{samples.map(s=><button key={s.id} aria-pressed={active===s} className={`sample-${s.color} ${active===s?'selected':''}`} onClick={()=>{setSelection(s.id);setResult('');}}><span className="sample-badge">{s.mark}</span>{s.id}</button>)}</div><h3 className={`sample-current sample-${active.color}`}><span className="sample-badge">{active.mark}</span>目前檢測：{active.id}</h3><div className="sample-tests"><article><span className={`dish ${shown&&active.iodine==='藍黑色'?'blue':''}`} aria-hidden="true"/><h3>分裝 1：碘液</h3><p>{shown?active.iodine:'尚未操作'}</p></article><article><span className={`tube ${shown&&active.benedict==='橙紅色'?'orange':''}`} aria-hidden="true"/><h3>分裝 2：本氏液＋水浴</h3><p>{shown?active.benedict:'尚未操作'}</p></article></div><button className="primary" disabled={!!shown} onClick={()=>setChoices(c=>({...c,['seen-'+active.id]:'yes'}))}>完成兩份檢測，觀察結果</button>{shown&&<div className="discovery"><label>目前最合適的結論<select value={choices['claim-'+active.id]||''} onChange={e=>choose('claim-'+active.id,e.target.value)}><option value="">選擇結論</option><option>檢出澱粉，未檢出本氏液可測糖分</option><option>未檢出澱粉，檢出本氏液可測糖分</option><option>兩項均未檢出，不能排除其他養分</option><option>兩項陰性代表沒有任何養分</option></select></label><button className="outline" disabled={!choices['claim-'+active.id]} onClick={()=>{const correct=active.iodine==='藍黑色'?'檢出澱粉，未檢出本氏液可測糖分':active.benedict==='橙紅色'?'未檢出澱粉，檢出本氏液可測糖分':'兩項均未檢出，不能排除其他養分';if(choices['claim-'+active.id]===correct){setChoices(c=>({...c,['interpreted-'+active.id]:'yes'}));setResult('結論符合證據，請切換其他樣本繼續比較。');}else setResult('請分別對照兩種試劑，且不要推論所有養分。');}}>檢查結論</button><p role="status">{result}</p></div>}<button className="outline exploration-end" disabled={samples.some(s=>!choices['interpreted-'+s.id])} onClick={()=>complete('三份樣本比較完成。不同檢測結果需分別解釋。')}>完成三份樣本鑑定</button></section>;
 }
 return null;
}

export function ObservationTable({rows}:{rows:string[][]}){return <div className="observation-table"><table><caption className="sr-only">預測與觀察紀錄</caption><thead><tr><th>樣本</th><th>我的預測</th><th>觀察結果</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((c,i)=>i===0?<th scope="row" key={i}>{c}</th>:<td key={i}>{c}</td>)}</tr>)}</tbody></table></div>;}

export function ReadingEvidence({onDone,done}:{onDone:()=>void;done:boolean}){
 const [sample,setSample]=useState('');const [feedback,setFeedback]=useState('');
 return <div className="reading-evidence"><section className="card evidence-record"><h2><DesignIcon name="flask"/>檢測結果整理</h2><div className="observation-table"><table><caption className="sr-only">紙樣與對照的碘液結果</caption><thead><tr><th>樣本</th><th>加碘液後</th></tr></thead><tbody>{[['紙樣 A','紫紅色'],['紙樣 B','黃褐色']].map(r=><tr key={r[0]}><th>{r[0]}</th><td>{r[1]}</td></tr>)}</tbody></table></div><div className="observation-table"><table><caption>已知對照組（供參考）</caption><tbody>{[['澱粉液','藍黑色'],['水','黃褐色']].map(r=><tr key={r[0]}><th>{r[0]}</th><td>{r[1]}</td></tr>)}</tbody></table></div></section><section className="card evidence-question"><h2><span className="orange-question">?</span>想一想</h2><h3>根據紀錄，哪份紙樣檢出澱粉？</h3><div className="reading-choices">{['紙樣 A','紙樣 B','兩份都檢出澱粉'].map(x=><label key={x}><input type="radio" name="reading-evidence" checked={sample===x} onChange={()=>{setSample(x);setFeedback('');}}/>{x}</label>)}</div><button className="primary" disabled={!sample} onClick={()=>{if(sample==='紙樣 A'){setFeedback('A 呈紫紅色，支持檢出澱粉；B 的結論僅限本次未檢出。');onDone();}else setFeedback('請回看 A、B 的顏色，紫紅色與藍黑色都可代表澱粉陽性。');}}>檢查答案</button>{feedback&&<p role="status" className="discovery">{feedback}</p>}{done&&<small>✓ 已完成證據閱讀</small>}</section></div>;
}
