'use client';
import {useEffect,useRef,useState} from 'react';
import {PAGES,type Question} from './course-data';
import {STORAGE_KEY,fresh,readLocal,recordAnswer,pageComplete,pageReadyForNext,canAccessPage,resolvePage,totalPoints,completedCount,type CourseState,type Identity,type ActivityResult} from './course-state';
import {Art} from './course-art';
import {LeafMark,DesignIcon} from './design-elements';
import {PracticeQuestion,Assessment} from './course-questions';
import {Guide,Exploration,ReadingEvidence} from './course-explorations';
import {Game,Challenge} from './course-games';
import {ScoreSyncPanel} from './score-sync-panel';

function Home({state,onStart,demo=false}:{state:CourseState;onStart:(i:Identity)=>void;demo?:boolean}){
 const [identity,setIdentity]=useState(state.identity);const changed=state.started&&JSON.stringify(identity)!==JSON.stringify(state.identity);
 return <><section className="home-hero"><div className="hero-copy"><h1>食物中的<br/>養分與能量<span className="title-sparks" aria-hidden="true">╱</span></h1><p className="hero-subtitle">從餐桌出發，用證據認識養分。</p></div><div className="hero-art"><Art kind="home"/></div></section>
 <div className="home-bottom"><section className="card passport"><div className="passport-heading"><DesignIcon name="send"/><h2>開始你的學習</h2><p>填寫資料，展開你的虛擬探索之旅！</p></div><form onSubmit={e=>{e.preventDefault();onStart({classroom:identity.classroom.trim(),seat:identity.seat.trim(),name:identity.name.trim()});}}><div className="identity-fields">{(['classroom','seat','name'] as const).map((k,i)=><label key={k}>{['班級','座號','姓名'][i]}<input required maxLength={k==='seat'?3:24} inputMode={k==='seat'?'numeric':'text'} value={identity[k]} placeholder={['請輸入班級','請輸入座號','請輸入姓名'][i]} onChange={e=>setIdentity(v=>({...v,[k]:e.target.value}))}/></label>)}</div><button className="primary large" disabled={Object.values(identity).some(v=>!v.trim())}>{state.started&&!changed?'繼續學習　→':'開始學習　→'}</button>{changed&&<p className="reset-notice">{demo?'資料已變更。開始後會重新建立本次教師示範資料。':'資料已變更。開始後會清除上一位同學在本機的答案與成績，建立新的學習紀錄。'}</p>}</form></section>
 <section className="journey-preview">{[['search','辨認六大養分','認識食物中的六大養分，了解其特徵。'],['flask','使用虛擬試劑觀察','透過虛擬探索操作，觀察食物可能呈現的變化。'],['chart','根據結果說明理由','分析觀察結果，提出合理的理由，用證據支持結論。']].map(([icon,t,p])=><div key={t}><DesignIcon name={icon}/><div><h3>{t}</h3><p>{p}</p></div></div>)}</section><p className="home-storage-note">學習進度保存在這個瀏覽器，班級、座號、姓名與成績會上傳到老師的成績表。填寫資料後，依序完成任務即可解鎖下一頁。</p></div></>;
}

function Summary({done,onDone}:{done:boolean;onDone:()=>void}){
 const [active,setActive]=useState('養分');const [seen,setSeen]=useState<string[]>([]);
 const content:Record<string,{title:string;items:string[]}>={養分:{title:'把「供能」與「功能」分開思考',items:['醣類、蛋白質、脂質可供能，也有構成或儲存等用途。','水、礦物質與維生素不供能，但仍維持必要生理功能。','一份食物可能含多種養分；六大養分不是六大類食物。']},檢測:{title:'每一種試劑，回答不同問題',items:['碘液：黃褐色 → 藍黑色或紫紅色，支持檢出澱粉。','本氏液：樣本 2 mL＋試劑 2 mL、混勻並隔水加熱；陽性支持含可測糖分。','本氏液陽性不等於只有葡萄糖；未完成加熱不能直接判陰性。']},證據:{title:'讓結論的範圍，和證據一樣大',items:['樣本不同，其餘條件一致；對照提供重要比較。','同一樣本分裝後，分別使用不同試劑。','陰性只代表本次未檢出該項，不代表沒有任何養分。']}};
 return <section className="card concept-map"><span className="label">你的知識地圖</span><h2>從養分，到有證據的結論</h2><p>依序展開三個節點，回顧你在研究所找到的線索。</p><div className="concept-nodes">{Object.keys(content).map((key,i)=><button key={key} className={active===key?'selected':''} onClick={()=>{setActive(key);setSeen(s=>s.includes(key)?s:[...s,key]);}}><small>0{i+1}</small><strong>{key}</strong><span>{seen.includes(key)?'✓ 已回顧':'展開線索'}</span></button>)}</div><article className="concept-detail"><h3>{content[active].title}</h3><ul>{content[active].items.map(t=><li key={t}>{t}</li>)}</ul></article><button className="primary" disabled={seen.length!==3||done} onClick={onDone}>{done?'已完成重點整理':`完成重點整理（${seen.length}／3）`}</button></section>;
}

function exportData(state:CourseState){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='養分研究所-本機學習紀錄.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Results({state,navigate}:{state:CourseState;navigate:(id:string)=>void}){
 const a=state.activities;const pending=Object.values(state.answers).filter(x=>x.pending).length;const mastered=Object.values(state.answers).filter(x=>x.done).length;
 const cards=[{id:'assessment-one',name:'養分理解檢查',label:'形成性評量一',value:a['assessment-one']?.[0]?.score,max:100,note:'首次作答成績'},{id:'assessment-two',name:'檢測推理檢查',label:'形成性評量二',value:a['assessment-two']?.[0]?.score,max:100,note:'首次作答成績'},{id:'game-one',name:'養分任務闖關',label:'遊戲任務一',value:a['game-one']?.length?Math.max(...a['game-one'].map(r=>r.score)):undefined,max:60,note:`首次 ${a['game-one']?.[0]?.score??'—'} 分・顯示最高分`},{id:'game-two',name:'檢測判斷挑戰',label:'遊戲任務二',value:a['game-two']?.length?Math.max(...a['game-two'].map(r=>r.score)):undefined,max:60,note:`首次 ${a['game-two']?.[0]?.score??'—'} 分・顯示最高分`},{id:'challenge',name:'養分極限挑戰',label:'極限挑戰',value:a.challenge?.length?Math.max(...a.challenge.map(r=>r.score)):undefined,max:60000,note:'本人的最高挑戰紀錄'},{id:'nutrients',name:'一步一步累積的理解',label:'學習得分',value:totalPoints(state),max:120,note:`已掌握 ${mastered}／40 題${pending?`・${pending} 題待確認`:'・含 1 題教師確認簡答'}`}];
 return <div className="results-layout"><aside className="results-aside"><h2>養分研究所</h2><p>小小探索・大大發現</p><Art kind="resultsScene"/></aside><div className="results-panel"><div className="results-title"><h2>我的學習成果</h2><p>回顧這段時間的探索歷程，看看你在養分研究所的學習收穫！</p></div><section className="results-progress"><strong>學習進度</strong><div>{[{name:'養分',ids:['nutrients']},{name:'功能',ids:['materials','essentials']},{name:'檢測',ids:['iodine','benedict','fair-test','samples']},{name:'閱讀',ids:['reading']},{name:'挑戰',ids:['game-one','game-two','challenge']}].map(g=><div key={g.name}><span className={g.ids.every(id=>pageComplete(state,id))?'complete':''}>{g.ids.every(id=>pageComplete(state,id))?'✓':<DesignIcon name={g.name==='閱讀'?'book':g.name==='挑戰'?'flag':'flask'}/>}</span><b>{g.name}</b></div>)}</div><small>已完成 {completedCount(state)}／15 關{pending?`・${pending} 題待教師確認`:''}</small></section><div className="result-cards">{cards.map((c,i)=><article key={c.id} className={`result-card result-${i}`}><span className="result-icon"><DesignIcon name={['book','flask','target','search','flag','chart'][i]}/></span><h3>{i===5?'學習總分':c.name}</h3><div className="result-value">{c.value===undefined?'—':c.value.toLocaleString()}<small>／{c.max.toLocaleString()}</small></div><p>{c.note}</p><button className="text-button" onClick={()=>navigate(c.id)}>{c.value===undefined?'前往完成':'回去看看'} →</button></article>)}</div><section className="card result-next"><DesignIcon name="search"/><div><h3>接下來可以做什麼</h3><p>回看養分的功能，或重新觀察檢測紀錄。</p></div><button className="primary" onClick={()=>navigate('materials')}><DesignIcon name="book"/>複習養分功能</button><button className="outline" onClick={()=>navigate('iodine')}>重看檢測證據</button></section><div className="results-actions"><button className="primary" onClick={()=>navigate('home')}><DesignIcon name="home"/>回到首頁</button><button className="outline" onClick={()=>navigate('guide')}><DesignIcon name="book"/>查看課程地圖</button></div><details className="result-notes card"><summary>查看待完成項目與計分說明</summary><p>一般練習首次答對 3 分、第二次 2 分、第三次起 1 分，不另扣分。閱讀簡答最高 3 分須由教師確認；本機版只保存原文，系統可自動累積上限為 117 分。</p><div className="unfinished-links">{PAGES.filter(p=>!['home','results'].includes(p.id)&&!pageComplete(state,p.id)).map(p=><button key={p.id} onClick={()=>navigate(p.id)}>{p.short}{p.id==='reading'&&pending?'・待確認':''} →</button>)}</div><button className="outline" onClick={()=>exportData(state)}>下載本機學習紀錄</button></details></div></div>;
}

function TeacherEntry({onUnlock,onClose}:{onUnlock:()=>void;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [code,setCode]=useState('');const [error,setError]=useState('');
 useEffect(()=>{const element=dialog.current;element?.showModal();return()=>element?.close();},[]);
 return <dialog ref={dialog} className="teacher-mode-dialog" aria-labelledby="teacher-mode-title" onCancel={onClose}><form onSubmit={e=>{e.preventDefault();if(code==='55688')onUnlock();else setError('密碼不正確，請重新輸入。');}}><h2 id="teacher-mode-title">教師模式</h2><p>輸入密碼後，可自由瀏覽全課程、任意切換頁面。</p><label>教師模式密碼<input autoFocus required type="password" value={code} onChange={e=>setCode(e.target.value)} autoComplete="off" aria-invalid={!!error} aria-describedby={error?'teacher-mode-error':undefined}/></label><p id="teacher-mode-error" role="status">{error}</p><div className="actions"><button className="primary">開啟教師模式</button><button className="outline" type="button" onClick={onClose}>取消</button></div></form></dialog>;
}

export default function CourseApp(){
 const [state,setState]=useState<CourseState>(fresh);const [ready,setReady]=useState(false);const [requestedPageId,setRequestedPageId]=useState('home');const [toast,setToast]=useState('');const [storageError,setStorageError]=useState('');const [teacher,setTeacher]=useState(false);const [teacherOpen,setTeacherOpen]=useState(false);const nav=useRef<HTMLElement>(null);const studentSnapshot=useRef<CourseState|null>(null);
 const pageId=resolvePage(state,requestedPageId,teacher);
 const leaveTeacher=()=>{if(studentSnapshot.current)setState(studentSnapshot.current);studentSnapshot.current=null;setTeacher(false);setToast('已離開教師模式，恢復學生學習進度。');};
 useEffect(()=>{if(!ready)return;if(pageId!==requestedPageId){setRequestedPageId(pageId);window.history.replaceState(null,'','#'+pageId);setToast('這一頁尚未解鎖，請先完成目前的任務。');}},[pageId,requestedPageId,ready]);
 useEffect(()=>{const saved=readLocal();if(!saved.sessionId)saved.sessionId=crypto.randomUUID();setState(saved);const route=()=>{let id=window.location.hash.slice(1);if(id==='course-main')return;if(id==='lesson')id='iodine';setRequestedPageId(PAGES.some(p=>p.id===id)?id:'home');};route();window.addEventListener('hashchange',route);setReady(true);return()=>window.removeEventListener('hashchange',route);},[]);
 useEffect(()=>{if(!ready||teacher)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));setStorageError('');}catch{setStorageError('瀏覽器暫時無法保存資料。本次畫面仍可操作，離開前請下載學習紀錄。');}},[state,ready,teacher]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{nav.current?.querySelector('[aria-current="page"]')?.scrollIntoView({block:'nearest',inline:'center'});},[pageId,ready]);
 const navigate=(id:string)=>{const target=resolvePage(state,id,teacher);if(target!==id)setToast('這一頁尚未解鎖，請先完成目前的任務。');window.location.hash=target;setRequestedPageId(target);window.scrollTo({top:0,behavior:'instant'});};
 const explored=()=>setState(s=>s.explored.includes(pageId)?s:{...s,explored:[...s.explored,pageId]});
 const answer=(q:Question,a:string[],correct:boolean|null)=>{const id=crypto.randomUUID();setState(s=>recordAnswer(s,q,a,correct,id));if(correct){const points=Math.max(1,3-(state.answers[q.id]?.attempts||0));setToast(`答對了！學習得分 ＋${points}`);}else if(correct===null)setToast('簡答已保存，待教師確認。');};
 const finish=(r:ActivityResult)=>setState(s=>{const list=s.activities[pageId]||[];if(pageId.startsWith('assessment')&&list.length)return s;return {...s,activities:{...s.activities,[pageId]:[...list,r]}};});
 const start=(identity:Identity)=>{if(teacher){const demo=fresh(identity);demo.sessionId=crypto.randomUUID();demo.started=true;setState(demo);window.location.hash='guide';setRequestedPageId('guide');return;}if(JSON.stringify(identity)!==JSON.stringify(state.identity)){const next=fresh(identity);next.sessionId=crypto.randomUUID();next.started=true;setState(next);setTeacher(false);studentSnapshot.current=null;setTeacherOpen(false);setToast('已建立新的學習通行證。');}else setState(s=>({...s,started:true}));window.location.hash='guide';setRequestedPageId('guide');window.scrollTo({top:0,behavior:'instant'});};
 const page=PAGES.find(p=>p.id===pageId)!;const index=PAGES.indexOf(page);const done=pageComplete(state,pageId);const readyForNext=pageReadyForNext(state,pageId);const pending=Object.values(state.answers).filter(a=>a.pending).length;
 if(!ready)return <main className="loading"><span className="brand-mark">◈</span><p>正在打開養分研究所……</p></main>;
 return <><a className="skip-link" href="#course-main">跳至課程內容</a><header className={`site-header ${pageId==='home'?'home-header':''}`}><div className="header-inner"><button className="teacher-trigger outline" aria-pressed={teacher} aria-label={teacher?'離開教師模式':'教師模式'} onClick={()=>teacher?leaveTeacher():setTeacherOpen(true)}><DesignIcon name="person"/>{teacher?'離開教師模式':'教師模式'}</button><button className="brand" onClick={()=>navigate('home')}><LeafMark/><span>食物中的養分與能量<small>探索食物・認識養分・發現生活中的科學</small></span></button><div className="header-meta"><span className="student-badge">{state.started?`${state.identity.classroom}｜${state.identity.name}`:''}</span><button className="text-button" onClick={()=>navigate(pageId==='home'?'guide':'home')}>{pageId==='home'?'課程地圖':'回到首頁'}</button><details className="review-mode"><summary>學習說明</summary><p>完成當頁任務後解鎖下一頁。教師輸入密碼後可自由瀏覽全課程；示範操作不改變學生進度。</p></details></div></div></header>
 {pageId!=='home'&&<div className="course-toolbar"><div className="nav-scroll-wrap"><button className="nav-scroll-control" aria-label="向前捲動課程導覽" onClick={()=>nav.current?.scrollBy({left:-420,behavior:'smooth'})}>‹</button><nav className="course-nav" ref={nav} aria-label="課程頁面">{PAGES.map((p,i)=><button key={p.id} disabled={!canAccessPage(state,p.id,teacher)} title={!canAccessPage(state,p.id,teacher)?'尚未解鎖，請先依序完成前面的任務':p.title} aria-label={!canAccessPage(state,p.id,teacher)?p.short+'（尚未解鎖）':p.short} aria-current={pageId===p.id?'page':undefined} onClick={()=>navigate(p.id)}><span className="nav-symbol">{!canAccessPage(state,p.id,teacher)?<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/><path d="M12 14v3"/></svg>:pageComplete(state,p.id)?'✓':<DesignIcon name={p.kind==='home'?'home':p.kind==='game'?'flag':p.kind==='reading'?'book':p.kind==='results'?'chart':p.kind==='lesson'?'flask':p.kind==='challenge'?'target':'note'}/>}</span><span>{p.short}</span></button>)}</nav><button className="nav-scroll-control" aria-label="向後捲動課程導覽" onClick={()=>nav.current?.scrollBy({left:420,behavior:'smooth'})}>›</button></div><div className="progress-line"><span style={{width:`${completedCount(state)/15*100}%`}}/></div><div className="progress-caption"><span>學習進度 {completedCount(state)}／15{pending?`・${pending} 題待教師確認`:''}</span><span>第 {index+1}／17 頁　學習得分 {totalPoints(state)} 分</span></div></div>}
 {storageError&&<div className="site-alert" role="alert">{storageError}<button className="outline" onClick={()=>exportData(state)}>下載紀錄</button></div>}
 {teacherOpen&&!teacher&&<TeacherEntry onUnlock={()=>{studentSnapshot.current=state;setTeacher(true);setTeacherOpen(false);setToast('教師示範操作不會保存到學生的學習紀錄。');}} onClose={()=>setTeacherOpen(false)}/>}
 {teacher&&<div className="teacher-mode-status" role="status">教師模式已開啟・全課程解鎖・示範操作不保存至學生進度</div>}
 <ScoreSyncPanel state={state} teacher={teacher}/>
 <main id="course-main" className={`course-main page-${pageId}`}>{!state.started&&pageId!=='home'&&<div className="identity-reminder">目前為未具名試用。建立通行證會重新開始紀錄。<button className="text-button" onClick={()=>navigate('home')}>填寫通行證 →</button></div>}
 <div key={`${state.sessionId}-${teacher?'teacher':'student'}-${pageId}`}>
 {page.kind==='home'?<Home state={state} onStart={start} demo={teacher}/>:<><div className="page-heading"><div><h1><DesignIcon name={page.kind==='lesson'?'flask':page.kind==='reading'?'book':page.kind==='game'?'flag':'note'}/>{page.title}</h1>{page.source&&<p className="source-label">{page.source}</p>}</div><span className={`completion-pill ${done?'done':''}`}>{done?'✓ 本頁已完成':page.kind==='results'?'持續累積中':pageId==='reading'&&pending?(readyForNext?'已提交・簡答待確認':'簡答待確認'):'探索進行中'}</span></div>
 {page.kind==='guide'&&<Guide done={done} onDone={explored}/>}
 {page.kind==='lesson'&&<><section className="lesson-reading card"><span className="label">讀一讀 · 找出關鍵線索</span>{page.paragraphs?.map(p=><p key={p}>{p}</p>)}</section><Exploration id={pageId} done={state.explored.includes(pageId)} onDone={explored}/></>}
 {page.kind==='assessment'&&<Assessment questions={page.questions!} first={state.activities[pageId]?.[0]} onFinish={finish}/>}
 {page.kind==='game'&&<Game variant={pageId==='game-one'?1:2} history={state.activities[pageId]||[]} onFinish={finish}/>}
 {page.kind==='reading'&&<div className="reading-layout"><article className="reading-article"><div className="reading-title"><span className="label"><DesignIcon name="book"/>閱讀理解</span><span className="virtual-chip">虛擬觀察紀錄</span></div><h2>紙張也有澱粉嗎？</h2><p className="reading-lead">有些紙張製作時會加入澱粉，使表面更平滑。不同紙樣的檢測結果可能不同，應根據觀察下結論。</p><Art kind="paperScene" zoom/><details className="reading-context"><summary>閱讀完整情境與檢測條件</summary>{page.paragraphs?.map(p=><p key={p}>{p}</p>)}</details></article><ReadingEvidence done={state.explored.includes(pageId)} onDone={explored}/></div>}
 {page.kind==='summary'&&<Summary done={done} onDone={explored}/>}
 {page.kind==='challenge'&&<Challenge history={state.activities.challenge||[]} onFinish={finish}/>}
 {page.kind==='results'&&<Results state={state} navigate={navigate}/>}
 {['lesson','reading'].includes(page.kind)&&<section className="practice-section"><div className="section-heading"><div><span className="label">CHECK YOUR DISCOVERY</span><h2>換你試一試</h2><p>每題獨立作答。答錯後先讀提示，再重新作答。</p></div><span className="practice-count">{page.questions?.filter(q=>state.answers[q.id]?.done).length}／5 已掌握</span></div>{page.questions?.map((q,i)=><PracticeQuestion key={q.id} q={q} index={i} record={state.answers[q.id]} onSubmit={answer}/>)}</section>}
 </>}
 </div>
 {pageId!=='home'&&<footer className="page-footer"><button className="outline" disabled={index===0} onClick={()=>navigate(PAGES[index-1].id)}>← {PAGES[index-1]?.short}</button><p>{teacher?'教師模式：可自由切換頁面。':readyForNext?(done?'本頁完成，已解鎖下一頁。':'回答已提交，簡答待教師確認；可前往下一頁。'):pageId==='results'?'學習進度保存在目前瀏覽器，成績上傳狀態請見頁面上方。':page.kind==='lesson'?'完成探索，並答對本頁 5 題後解鎖下一頁。':page.kind==='reading'?'完成閱讀探索、答對選擇題並提交簡答後解鎖下一頁。':page.kind==='assessment'?'回答全部題目並提交評量後解鎖下一頁。':page.kind==='game'?'完成 6 回合並查看本次成果後解鎖下一頁。':page.kind==='challenge'?'完成一場極限挑戰後解鎖成果頁。':page.kind==='guide'?'完成圓形示範題後解鎖下一頁。':'展開三個節點，按下完成重點整理後解鎖下一頁。'}</p>{index<PAGES.length-1?<button className="primary" disabled={!canAccessPage(state,PAGES[index+1].id,teacher)} onClick={()=>navigate(PAGES[index+1].id)}>{PAGES[index+1].short} →</button>:<button className="primary" onClick={()=>navigate('home')}>回到首頁</button>}</footer>}
 <div className="site-footer"><span>養分研究所 · 國中自然科學</span><span>觀察，比較，再下結論。</span></div></main>{toast&&<div className="toast" role="status">{toast}</div>}</>;
}
